### ISSUE TITLE
[enhancement] Chilling in same rooms after death.

### ISSUE THREAD

**Issue by iojforever** [Michal78900/WaitAndChillReborn#2]
Main idea of that plugin is to let people relax while game starting instead of watching how black screen looks like. I think the same feature can be used after death to let people run from side to side and talk with each others or stay away from people who can annoy them. It can be disabled via config. 

- "Why you ask to add it instead of asking new plugin?" 

You see, there is another plugin made by you, and its called "respawntimer" 
Adding support for it will do the thing instead of nothing being showed on players screen. 

- New Config option variation:
- [Only as idea, you can do whatev ya want] 

WaitAndChillReborn
# Is the plugin enabled?
is_enabled: bool
... 
... 
... 
# Should spectators Appear in the lounge after death? 
SpecChill: bool
SpecChill_rooms:
- TOWER1
- TOWER2

**Comment by Michal78900** [comment]
Basically this idea is GhostSpectator without being a ghost. It would be hard to implement and also not very helpful since GhostSpecator exists. Thanks for the idea tho.
